services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./osp_nce/backend:/app/osp_nce/backend
      - ./osp_nce/shared:/app/osp_nce/shared
      - ./osp_nce/sql:/app/osp_nce/sql
    env_file:
      - ./.env
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./osp_nce/frontend:/app/osp_nce/frontend
      - ./osp_nce/shared:/app/osp_nce/shared
      - ./assets:/app/assets
    env_file:
      - ./.env
    depends_on:
      - backend
