services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./src/osp_nce/backend:/app/src/osp_nce/backend
      - ./src/osp_nce/shared:/app/src/osp_nce/shared
    env_file:
      - ./.env
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./src/osp_nce/frontend:/app/src/osp_nce/frontend
      - ./src/osp_nce/shared:/app/src/osp_nce/shared
    env_file:
      - ./.env
    depends_on:
      - backend
